[package]
name = "rumpsteak-generate"
version = "0.1.0"
authors = ["Zak Cutner <me@zakcutner.uk>"]
edition = "2018"
description = "Session types for asynchronous communication between multiple parties."
readme = "../README.md"
repository = "https://github.com/zakcutner/rumpsteak"
license = "MIT"
keywords = ["async", "deadlock", "safety", "session", "types"]
categories = ["asynchronous", "concurrency"]

[[bin]]
name = "rumpsteak-generate"
required-features = ["clap"]

[features]
default = ["clap"]

[dependencies]
<<<<<<< HEAD
askama = { git = "https://github.com/djc/askama", rev = "b93ce46" }
clap = { version = "3.1.0", optional = true, features=["derive"]}
=======
askama = { git = "https://github.com/djc/askama", rev = "95e346e" }
clap = { version = "3.0.0-rc.7", optional = true, features=["derive"]}
>>>>>>> 2a26e53e21b947caa80d8e0e3d4df7fe174659a8
heck = "0.3"
indexmap = "1.6"
pest = "2.1"
pest_derive = "2.1"
petgraph = "0.5"
dot-parser = "*"
